apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser-deployment
  labels:
    app: parser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: parser-service:0.1.0
          imagePullPolicy: Never # Force to use the local image
          args:
            - "-ip"
            - "0.0.0.0"
            - "-port"
            - "8080"
          ports:
            - containerPort: 8080