// > protoc --go_out . --go_opt paths=source_relative --go-grpc_out . --go-grpc_opt paths=source_relative proto/*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: proto/parser.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RawPageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HtmlContent string `protobuf:"bytes,1,opt,name=html_content,json=htmlContent,proto3" json:"html_content,omitempty"`
}

func (x *RawPageData) Reset() {
	*x = RawPageData{}
	mi := &file_proto_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPageData) ProtoMessage() {}

func (x *RawPageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPageData.ProtoReflect.Descriptor instead.
func (*RawPageData) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *RawPageData) GetHtmlContent() string {
	if x != nil {
		return x.HtmlContent
	}
	return ""
}

type ParsedPageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Availability string `protobuf:"bytes,2,opt,name=availability,proto3" json:"availability,omitempty"`
	Upc          string `protobuf:"bytes,3,opt,name=upc,proto3" json:"upc,omitempty"`
	PriceExclTax string `protobuf:"bytes,4,opt,name=price_excl_tax,json=priceExclTax,proto3" json:"price_excl_tax,omitempty"`
	Tax          string `protobuf:"bytes,5,opt,name=tax,proto3" json:"tax,omitempty"`
	Message      string `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"` // success/failure message
}

func (x *ParsedPageResponse) Reset() {
	*x = ParsedPageResponse{}
	mi := &file_proto_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedPageResponse) ProtoMessage() {}

func (x *ParsedPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedPageResponse.ProtoReflect.Descriptor instead.
func (*ParsedPageResponse) Descriptor() ([]byte, []int) {
	return file_proto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedPageResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParsedPageResponse) GetAvailability() string {
	if x != nil {
		return x.Availability
	}
	return ""
}

func (x *ParsedPageResponse) GetUpc() string {
	if x != nil {
		return x.Upc
	}
	return ""
}

func (x *ParsedPageResponse) GetPriceExclTax() string {
	if x != nil {
		return x.PriceExclTax
	}
	return ""
}

func (x *ParsedPageResponse) GetTax() string {
	if x != nil {
		return x.Tax
	}
	return ""
}

func (x *ParsedPageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_parser_proto protoreflect.FileDescriptor

var file_proto_parser_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0b, 0x52, 0x61, 0x77, 0x50, 0x61, 0x67, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x68, 0x74, 0x6d, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x74, 0x6d, 0x6c, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xb0, 0x01, 0x0a, 0x12, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x64, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x70, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x70, 0x63, 0x12, 0x24, 0x0a, 0x0e, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x5f, 0x65, 0x78, 0x63, 0x6c, 0x5f, 0x74, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x70, 0x72, 0x69, 0x63, 0x65, 0x45, 0x78, 0x63, 0x6c, 0x54, 0x61, 0x78, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x78, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x38, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x73, 0x65, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x0c, 0x2e, 0x52, 0x61, 0x77, 0x50, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x13,
	0x2e, 0x50, 0x61, 0x72, 0x73, 0x65, 0x64, 0x50, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72,
	0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_parser_proto_rawDescOnce sync.Once
	file_proto_parser_proto_rawDescData = file_proto_parser_proto_rawDesc
)

func file_proto_parser_proto_rawDescGZIP() []byte {
	file_proto_parser_proto_rawDescOnce.Do(func() {
		file_proto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_parser_proto_rawDescData)
	})
	return file_proto_parser_proto_rawDescData
}

var file_proto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_parser_proto_goTypes = []any{
	(*RawPageData)(nil),        // 0: RawPageData
	(*ParsedPageResponse)(nil), // 1: ParsedPageResponse
}
var file_proto_parser_proto_depIdxs = []int32{
	0, // 0: Parser.ParsePage:input_type -> RawPageData
	1, // 1: Parser.ParsePage:output_type -> ParsedPageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_parser_proto_init() }
func file_proto_parser_proto_init() {
	if File_proto_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_parser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_parser_proto_goTypes,
		DependencyIndexes: file_proto_parser_proto_depIdxs,
		MessageInfos:      file_proto_parser_proto_msgTypes,
	}.Build()
	File_proto_parser_proto = out.File
	file_proto_parser_proto_rawDesc = nil
	file_proto_parser_proto_goTypes = nil
	file_proto_parser_proto_depIdxs = nil
}
